Small demo for python 3.10(.13) import issue when a package is installed
in editable mode and a subfolder of the same name exists.

1. generate venv
./make_virtualenv <PATH_TO_PYTHON3.10>

2. test
cd test
./test.sh
